--
-- psql -h localhost -U $SQL_DATABASE_USER -d $SQL_DATABASE_NAME -W
-- Create the $SQL_DATABASE_USER user for the $SQL_DATABASE_NAME
--
CREATE ROLE $SQL_DATABASE_USER LOGIN NOSUPERUSER INHERIT CREATEDB CREATEROLE NOREPLICATION PASSWORD '$SQL_DATABASE_NAME';
--
-- Create the database
--
CREATE DATABASE $SQL_DATABASE_NAME OWNER $SQL_DATABASE_USER;
--
-- Create the schema
--
CREATE SCHEMA IF NOT EXISTS $SQL_SCHEMA_TABLE AUTHORIZATION $SQL_DATABASE_USER;
--
-- Grant privileges
--
GRANT ALL PRIVILEGES ON $SQL_DATABASE_NAME TO $SQL_DATABASE_USER;

-- SCRIPT BEGIN: set up connection and schema
\connect $SQL_DATABASE_NAME
set schema $SQL_SCHEMA_TABLE;
-- SCRIPT END
-- Table: "$SQL_SCHEMA_TABLE"
-- DROP TABLE "$SQL_SCHEMA_TABLE";
CREATE TABLE $SQL_SCHEMA_TABLE
(
	id bigserial NOT NULL,
$SQL_CREATECOLUMS
	CONSTRAINT pk_contact PRIMARY KEY (id)
)
WITH (
	OIDS=FALSE
);
ALTER TABLE $SQL_SCHEMA_TABLE
	OWNER TO $SQL_DATABASE_USER;

-- Index: $SQL_TABLE_INDEX_ID
-- DROP INDEX $SQL_TABLE_INDEX_ID;
CREATE INDEX $SQL_TABLE_INDEX_ID
  ON $SQL_SCHEMA_TABLE
  USING btree
  (id);

$SQL_TABLE_INDEX
